ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/laser_focus_zc550kl/show_lib/inc
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/laser_focus_zc550kl/laura/inc

obj-$(CONFIG_MSMB_CAMERA) += laura_interface.o
