#
# Makefile for the input misc drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_INPUT_UINPUT)		+= uinput.o

#+++ ASUS Alian_Shen "add BMA223"
obj-y += bma2x2.o
obj-y += bstclass.o
obj-y += kxtj9.o
#--- ASUS Alian_Shen "add BMA223"
