ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/laser_focus/show_lib/inc
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/laser_focus/laura/inc

obj-$(CONFIG_MSMB_CAMERA) += laura_debug.o
