#++++ ASUS_BSP Alian_Shen "Add compass for zc550KL"
ifneq ($(CONFIG_ASUS_ZC550KL_PROJECT),y)
        obj-y   += akm09911.o
endif
ifeq ($(CONFIG_ASUS_ZC550KL_PROJECT),y)
        obj-y   += akm09911_zc550kl.o
endif
#---- ASUS_BSP Alian_Shen "Add compass for zc550KL"
