#++++ ASUS_BSP Alian_Shen "Add compass for zc550KL"
ifneq ($(ASUS_BUILD_PROJECT), ZC550KL)
        obj-y   += akm09911.o
endif
ifeq ($(ASUS_BUILD_PROJECT), ZC550KL)
        obj-y   += akm09911_zc550kl.o
endif
#---- ASUS_BSP Alian_Shen "Add compass for zc550KL"
