ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/laser_focus_zc550kl
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/laser_focus_zc550kl/vl6180/inc
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/laser_focus_zc550kl/show_lib/inc

obj-$(CONFIG_MSMB_CAMERA) += msm_laser_focus_vl6180.o
obj-$(CONFIG_MSMB_CAMERA) += vl6180x_i2c.o
obj-$(CONFIG_MSMB_CAMERA) += vl6180x_api.o
