#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

ftxxxx-objs += ftxxxx_ts.o ftxxxx_ex_fun.o focaltech_ctl.o ini.o test_lib.o
obj-$(CONFIG_TOUCHSCREEN_FT5X46_ZC550KL) += ftxxxx.o
